### ISSUE TITLE
Nicer log of pre download summary

### ISSUE THREAD

**Issue by negebauer** [open-source-uc/sincding#6]
Change this
```
Found:
[ { name: 'Organización y Comportamiento en la Empresa',
    folders: 29,
    files: 78 },
  { name: 'Estructuras de Datos y Algoritmos',
    folders: 0,
    files: 0 },
  { name: 'Desarrollo de Software', folders: 1, files: 1 },
  { name: 'Topicos Avanzados de Sistemas Distribuidos',
    folders: 3,
    files: 32 } ]
Download:
[ { name: 'Organización y Comportamiento en la Empresa',
    folders: 0,
    files: 0 },
  { name: 'Estructuras de Datos y Algoritmos',
    folders: 0,
    files: 0 },
  { name: 'Desarrollo de Software', folders: 0, files: 0 },
  { name: 'Topicos Avanzados de Sistemas Distribuidos',
    folders: 0,
    files: 0 } ]
```

To a nicer format

**Comment by negebauer** [comment]
New log

```
Found:

- Organización y Comportamiento en la Empresa
  - folders: 30
  - files: 79

- Estructuras de Datos y Algoritmos
  - folders: 0
  - files: 0

- Desarrollo de Software
  - folders: 2
  - files: 6

- Topicos Avanzados de Sistemas Distribuidos
  - folders: 3
  - files: 33

Download:

- Organización y Comportamiento en la Empresa
  - folders: 0
  - files: 0

- Estructuras de Datos y Algoritmos
  - folders: 0
  - files: 0

- Desarrollo de Software
  - folders: 0
  - files: 0

- Topicos Avanzados de Sistemas Distribuidos
  - folders: 0
  - files: 0
```
